default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/images_hub_dev

test:
  <<: *default
  database: db/images_hub_test

production:
  <<: *default
  database: db/images_hub_production
